apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "webapp.fullname" . }}
  labels:
  {{- include "webapp.labels" . | nindent 4 }}
data:
  index.html: |
    This is a new line! <p>
    This exists only on the testing branch for now! <p>
    This is version {{ .Chart.AppVersion }} of our app, running in {{ .Values.appType }}


